version: '3.8'

services:
  db:
    image: postgres:15
    container_name: notes_pg_db
    environment:
      POSTGRES_DB: notes-editor-db
      POSTGRES_USER: xrendezvous
      POSTGRES_PASSWORD: Xzvv9843
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
